logo:
  subtitle: '全栈工程师|咖啡、足球、帕鲁世界！' # '文字1 | 文字2' (鼠标放上去会切换到文字2)

# 侧边栏主功能导航菜单
menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    - id: post  # 页面中高亮的 menu_id
      theme: '#1BCDFC' # 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
      icon: solar:documents-bold-duotone # 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
      title: 文章 # 标题
      url: / # 跳转链接，支持相对路径和绝对路径
    - id: wiki
      theme: '#3DC550'
      icon: solar:notebook-bookmark-bold-duotone
      title: 文档
      url: /wiki/
    - id: essays
      theme: '#FA6400'
      icon: solar:planet-bold-duotone
      title: 时光
      url: /essays/
    - id: socials
      theme: '#F44336'
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /socials/

copycode:
  enable: true
  js: /js/plugins/copycode.js
  default_text: '复制代码' # 按钮显示文字
  success_text: '已复制' # 复制成功信息

link:
  underline: true # true / false

######## Main ########
# 站点主结构树
site_tree:
  # -- 列表类页面 -- #
  # 主页配置
  home:
    sidebar: gfw
  # 博客列表页配置
  index_blog:
    base_dir: blog # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    sidebar: gfw #, recent, timeline # for categories/tags/archives
    nav_tabs:  # 近期发布 分类 标签 专栏 归档 and ...
    # '朋友文章': /friends/rss/
  # 博客专栏列表页配置
  index_topic:
    base_dir: topic # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 topic 的页面默认使用这里配置的 menu_id
  # 文档列表页配置
  index_wiki:
    base_dir: wiki # 只影响自动生成的页面路径
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    sidebar: gfw # for wiki
    nav_tabs:
    # 'more': https://github.com/xaoxuu
  # -- 内容类页面 -- #
  # 博客文章内页配置
  post:
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    sidebar: gfw # for pages using 'layout:post'
  # 博客专栏文章内页配置
  topic:
    menu_id: post
  # 文档内页配置
  wiki:
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    sidebar: gfw # for wiki
  # 作者信息配置
  author:
    base_dir: author # 只影响自动生成的页面路径
    menu_id: post
    sidebar: gfw
  # 错误页配置
  error_page:
    menu_id: post
    '404': '/404.html'
    sidebar: gfw
  # 其它自定义页面配置 layout: page
  page:
    sidebar: gfw
  essays:
    sidebar: gfw

inject:
  head:
    - <link href="https://cdn.bootcdn.net/ajax/libs/lxgw-wenkai-screen-webfont/1.7.0/style.min.css" rel="stylesheet">
  script:

style:
  darkmode: always
  sidebar:
    background-image: 'url(https://lab.celaraze.com:9999/blog/background-sidebar.jpg)'
    blur: true # 在图片上层增加高斯模糊效果（同时附带饱和度增强效果）
  font-family:
    body: '"LXGW WenKai Screen", "Microsoft Yahei", sans-serif'

comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    src: https://giscus.app/client.js
    data-repo: celaraze/blog-discussions # [在此输入仓库]
    data-repo-id: R_kgDOLMC0nQ # [在此输入仓库 ID]
    data-category: Announcements  # [在此输入分类名]
    data-category-id: DIC_kwDOLMC0nc4Cc1ct
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous

lazyload:
  enable: true # [hexo clean && hexo s] is required after changing this value.
  js: https://gcore.jsdelivr.net/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
  transition: blur # blur, fade
